#####
VAGRANTFILE_API_VERSION = "2"
BASE_OS_6 = "centos65"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

#todas las maquinas son iguales en recursos
config.vm.provider "virtualbox" do |v|
	v.cpus		= 2
	v.memory	= 2048
end


# provisionamiento base, comun para todos
config.vm.provision "shell", path: "inicia.sh", privileged: true
#



# DNS
	config.vm.define "servidor" do |box|
    	box.vm.box = BASE_OS_6
		box.vm.network "private_network", virtualbox__intnet: "portafolio", ip: "10.0.0.5"
 		#box.vm.network "forwarded_port", guest: 53, host: 53
		box.vm.hostname = "servidor"
	end

end



